# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

jobs:
  - job: Ubuntu_CI_Tests
    displayName: Ubuntu CI Tests
    condition: succeeded()

    pool:
      vmImage: ubuntu-18.04

    variables:
      testRunTitle: '$(build.sourceBranchName)-linux'
      testRunPlatform: linux

    steps:
    - script: apt-get update
    - script: apt-get -yq install gtk3
      displayName: 'Install dependencies'

    - task: CMake@1
      inputs:
        cmakeArgs: ..
